# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aroback

on:
  push:
    branches:
      - azurethree
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://machingback.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae58a0b38a374f3cbd3197a0b366dccc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9f89f2d070a4f0d929d65e6b69f3f3f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: machingback.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae58a0b38a374f3cbd3197a0b366dccc }}/helloworld00:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aroback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b1626bbf26c74922991bd5767f1059b9 }}
        images: 'machingback.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae58a0b38a374f3cbd3197a0b366dccc }}/helloworld00:${{ github.sha }}'